### ISSUE TITLE
前置摄像头图片有毒

### ISSUE THREAD

**Issue by KwanTang324** [WangYantao/android-camera-demos#2]
用前置摄像头拍照片的时候，图片翻转是有问题的。你都没试过

**Comment by WangYantao** [comment]
> 
> 
> 用前置摄像头拍照片的时候，图片翻转是有问题的。你都没试过

我这边正常的，你那什么问题能描述详细些嘛？？？（ps：你怎么知道我没试过）

**Comment by KwanTang324** [comment]
三星 S8

在 2019-08-01 16:59:24，"wangyt" <notifications@github.com> 写道：


用前置摄像头拍照片的时候，图片翻转是有问题的。你都没试过

我这边正常的，你那什么问题能描述详细些嘛？？？（ps：你怎么知道我没试过）
